;/*FB_PKG_DELIM*/

__d("CometExternalLinkedEntityRenderer_entity.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:{mask:!1},name:"CometExternalLinkedEntityRenderer_entity",selections:[{alias:null,args:[{kind:"Literal",name:"site",value:"www"}],kind:"ScalarField",name:"url",storageKey:'url(site:"www")'}],type:"Entity",abstractKey:"__isEntity"};e.exports=a}),null);
__d("CometTextLink.react",["CometLink.react","TetraText.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a,b){var d=a.color,e=a.type;a=babelHelpers.objectWithoutPropertiesLoose(a,["color","type"]);a=babelHelpers["extends"]({},a,{ref:b});return h.jsx(c("TetraText.react"),{color:d,type:e,children:h.jsx(c("CometLink.react"),babelHelpers["extends"]({},a,{color:d}))})}a.displayName=a.name+" [from "+f.id+"]";b=h.forwardRef(a);g["default"]=b}),98);
__d("GSUALoggingUtils",[],(function(a,b,c,d,e,f,g){"use strict";function a(a,b,c,d,e,f){if(b===!0)return"group_mall_featured_card";switch(a){case"homepage_stream":return"newsfeed";case"group":if(d==="GROUP_ANNOUNCEMENTS_FEED")return"group_mall_featured_tab";return f!==null?f==="DISCUSSION"?"group_mall_discussion":"group_mall_bsg_tab":(b=e)!=null?b:"group_mall_bsg_tab";case"groups_tab":return"groups_tab";case"group_serp":return"group_search";case"search_results_page":if(c==="group_posts"||c==="groups_home")return"group_tab_serp";return c==="top"||c==="posts"?"global_search_module_result":"group_mall_topics_feed";case"group_permalink":return"group_permalink";default:return"unknown"}}g.storyRenderLocationToSurface=a}),98);
__d("CometGSUALoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({group_id:"",referral_code:"unknown",referral_surface:"unknown",surface:"unknown"});g["default"]=b}),98);
__d("CometExternalLinkedEntityRenderer",["CometExternalLinkedEntityRenderer_entity.graphql","CometTextContext","CometTextLink.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react"),j=d("react").useContext;h!==void 0?h:h=b("CometExternalLinkedEntityRenderer_entity.graphql");function k(a){var b=a.entity;a=a.node;var d=j(c("CometTextContext"));return b.url==null?a:i.jsx(c("CometTextLink.react"),{color:"blueLink",href:b.url,target:"_blank",type:(b=d==null?void 0:d.type)!=null?b:"bodyLink4",children:a})}k.displayName=k.name+" [from "+f.id+"]";a=function(a,b){return i.jsx(k,{entity:b,node:a})};g["default"]=a}),98);
__d("ComposedInlineStyle",[],(function(a,b,c,d,e,f){e.exports=Object.freeze({NONE:0,BOLD:1,ITALIC:2,UNDERLINE:4,CODE:8,STRIKETHROUGH:16,SUBSCRIPT:32,SUPERSCRIPT:64,QUOTE:128,UNORDEREDLIST:256,LISTITEM:512,MEDIUM_WEIGHT:1024,SEMIBOLD:2048,HEADLINE1:4096,HEADLINE2:8192,HEADLINE3:16384,ORDEREDLIST:32768,HORIZONTALRULER:65536,TABLE:131072,TABLEDATA:262144,TABLEROW:524288,PARAGRAPH:1048576,LIGHTSTRIKETHROUGH:2097152,HEADLINE4:4194304,COPYABLE:8388608,LINEBREAK:16777216,PRE:33554432,EXPANDABLE:67108864,EXPANDABLETITLE:134217728,EXPANDABLEBODY:268435456,EXPANDABLECONTAINER:536870912,EXPANDABLESUMMARY:1073741824,SPOILER:2147483648})}),null);
__d("CometInlineEntityRenderer",["ComposedInlineStyle","TetraText.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");a=function(a,b){switch(b.inline_style){case"BOLD":case c("ComposedInlineStyle").BOLD:return h.jsx("b",{children:a});case"ITALIC":case c("ComposedInlineStyle").ITALIC:return h.jsx("i",{children:a});case"UNDERLINE":case c("ComposedInlineStyle").UNDERLINE:return h.jsx("u",{children:a});case"CODE":case c("ComposedInlineStyle").CODE:return h.jsx("code",{className:"xmjcpbm x1hjwid2 xnzlfwo xwjfhlt x4p5aij x1j85h84 x6mezaz",children:a});case"LIGHTSTRIKETHROUGH":case c("ComposedInlineStyle").LIGHTSTRIKETHROUGH:return h.jsx("s",{className:"x1ks1olk",children:a});case"STRIKETHROUGH":case c("ComposedInlineStyle").STRIKETHROUGH:return h.jsx("s",{children:a});case"SUBSCRIPT":case c("ComposedInlineStyle").SUBSCRIPT:return h.jsx("sub",{children:a});case"SUPERSCRIPT":case c("ComposedInlineStyle").SUPERSCRIPT:return h.jsx("sup",{children:a});case"QUOTE":case c("ComposedInlineStyle").QUOTE:return h.jsx("blockquote",{children:a});case"UNORDEREDLIST":case c("ComposedInlineStyle").UNORDEREDLIST:return h.jsx("ul",{className:"xtaz4m5 x1d52u69",children:a});case"ORDEREDLIST":case c("ComposedInlineStyle").ORDEREDLIST:return h.jsx("ol",{className:"x3yw8vx x1d52u69",children:a});case"LISTITEM":case c("ComposedInlineStyle").LISTITEM:return h.jsx("li",{children:a});case"HEADLINE1":case c("ComposedInlineStyle").HEADLINE1:return h.jsx(c("TetraText.react"),{isSemanticHeading:!0,type:"headlineEmphasized1",children:a});case"HEADLINE2":case c("ComposedInlineStyle").HEADLINE2:return h.jsx(c("TetraText.react"),{isSemanticHeading:!0,type:"headlineEmphasized2",children:a});case"HEADLINE3":case c("ComposedInlineStyle").HEADLINE3:return h.jsx(c("TetraText.react"),{isSemanticHeading:!0,type:"headlineEmphasized3",children:a});case"HORIZONTALRULER":case c("ComposedInlineStyle").HORIZONTALRULER:return h.jsx("hr",{});case"LINEBREAK":case c("ComposedInlineStyle").LINEBREAK:return h.jsx("br",{});default:return a}};g["default"]=a}),98);
__d("makeImmutable",[],(function(a,b,c,d,e,f){"use strict";function a(a){throw new Error("This empty "+((a=a)!=null?a:"Object")+" cannot be mutated.")}function b(a,b){return a}f["default"]=b}),66);
__d("emptyArray",["makeImmutable"],(function(a,b,c,d,e,f,g){"use strict";a=c("makeImmutable")([],["copyWithin","fill","pop","push","reverse","shift","sort","splice","unshift"]);b=a;g["default"]=b}),98);
__d("useShallowEqualMemo",["shallowEqual","useCustomEqualityMemo"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return c("useCustomEqualityMemo")(a,c("shallowEqual"))}g["default"]=a}),98);
__d("castToEnum",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){var d=Object.keys(b);for(var e=0;e<d.length;e++)if(b[d[e]]===a)return b[d[e]];return c}f["default"]=a}),66);
__d("BaseTypeaheadBaseStaticDataSource",["BaseTypeaheadDataCacheProvider","BaseTypeaheadInMemoryMapDataCache","baseTypeaheadStartsWithMatchBuilder"],(function(a,b,c,d,e,f,g){"use strict";a=function(){function a(a){var b=a.entries,d=a.keyBuilder;a=a.matchBuilder;a=a===void 0?c("baseTypeaheadStartsWithMatchBuilder"):a;this.$1=new(c("BaseTypeaheadDataCacheProvider"))({cache:new(c("BaseTypeaheadInMemoryMapDataCache"))(),keyBuilder:d,matchBuilder:a});this.$1.add(b)}var b=a.prototype;b.fetchCache=function(a){var b=a.query;return{entries:this.$1.match(b),params:a}};return a}();g["default"]=a}),98);
__d("memoizeByReference",["MemoizationInstrumentation"],(function(a,b,c,d,e,f,g){"use strict";var h=typeof WeakMap==="function";function a(a,b){b===void 0&&(b=a.name||"unknown");var c=h?new WeakMap():new Map(),e=function(e){var f=d("MemoizationInstrumentation").onFunctionCall("memoizeByReference",b);if(c.has(e)){var g=c.get(e);if(g!==void 0){f&&f(!0);return g[0]}}g=a(e);c.set(e,[g]);f&&f(!1);return g};return e}g["default"]=a}),98);
__d("getGraphQLEnumSafe",["flipObject","memoizeByReference"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b){if(b==null)return null;a=h(a);return!Object.prototype.hasOwnProperty.call(a,b)?null:a[b]}var h=c("memoizeByReference")(c("flipObject"));g["default"]=a}),98);/*FB_PKG_DELIM*/
__d("NullStateNoResults",["cr:3584"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:3584")}),98);
__d("NullStateNoResultsFB",["IconSource","bx"],(function(a,b,c,d,e,f,g){"use strict";a={dark:new(c("IconSource"))("nullStateGlyphs",c("bx").getURL(c("bx")("1160064")),112),"default":new(c("IconSource"))("nullStateGlyphs",c("bx").getURL(c("bx")("1160065")),112)};g["default"]=a}),98);
__d("XCometGroupsTabDiscoverControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/discover/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometGroupsTabEngageControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/groups/feed/",Object.freeze({inline_composer_post:!1}),void 0);b=a;g["default"]=b}),98);
__d("GroupsCometNullState.react",["fbt","CometCard.react","NullStateMedia","NullStateNoResults","TetraButton.react","TetraNullState.react","XCometGroupsTabDiscoverControllerRouteBuilder","XCometGroupsTabEngageControllerRouteBuilder","react"],(function(a,b,c,d,e,f,g,h){"use strict";var i=d("react"),j=c("XCometGroupsTabDiscoverControllerRouteBuilder").buildURL({}),k=c("XCometGroupsTabEngageControllerRouteBuilder").buildURL({}),l=h._("__JHASH__KMFjEn2xtRV__JHASH__"),m=h._("__JHASH__NG6nLliU94j__JHASH__");function a(a){a=a.subTab;a=a!=="feed";return i.jsx("div",{className:"x1yztbdb",role:"article",children:i.jsx(c("CometCard.react"),{background:"white",dropShadow:1,children:i.jsx(c("TetraNullState.react"),{action:i.jsx(c("TetraButton.react"),{label:a?m:l,linkProps:{url:a?k:j}}),body:h._("__JHASH__K5Oe-W3kYnD__JHASH__"),headline:h._("__JHASH__XcMrMBe3VX0__JHASH__"),icon:a?c("NullStateNoResults"):c("NullStateMedia")})})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("useGroupMarkPostsAsReadUpdate",["CometRelay","react","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useCallback;function a(){var a=d("CometRelay").useRelayEnvironment();return h(function(b){if(b==null){c("recoverableViolation")("Group null for left rail item","groups_comet");return}a.commitUpdate(function(a){a=a.get(b);a!=null&&(a.setValue(0,"unread_count"),a.setValue(!1,"should_show_community_panel_badge"))})},[a])}g["default"]=a}),98);
__d("useSearchCometResultsSearchTypeFromURL",["CometRouteParams"],(function(a,b,c,d,e,f,g){"use strict";function a(){var a=d("CometRouteParams").useRouteParams();a=a.searchtype;a=a!=null?a:null;return a}g["default"]=a}),98);
__d("SearchCometResultsEndOfResultsNotice.react",["fbt","CometColumn.react","CometColumnItem.react","TetraText.react","react"],(function(a,b,c,d,e,f,g,h){"use strict";var i=d("react");function a(a,b){return i.jsx(c("CometColumn.react"),{paddingTop:12,paddingVertical:0,ref:b,spacing:8,children:i.jsx(c("CometColumnItem.react"),{children:i.jsx(c("TetraText.react"),{align:"center",color:"secondary",type:"body3",children:h._("__JHASH__ZJcwwdMlcVK__JHASH__")})})})}a.displayName=a.name+" [from "+f.id+"]";b=i.forwardRef(a);g["default"]=b}),98);
__d("CommunityVerticalsEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1032");c=b("FalcoLoggerInternal").create("community_verticals_event",a);e.exports=c}),null);
__d("useCometTypeaheadStaticDataSource",["BaseTypeaheadBaseStaticDataSource","BaseTypeaheadPayloadDecoratorAddLimit","react","useDeepEqualMemo"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useMemo;function a(a){var b=a.limit;a=babelHelpers.objectWithoutPropertiesLoose(a,["limit"]);var d=h(function(){return c("BaseTypeaheadPayloadDecoratorAddLimit")(b)},[b]),e=c("useDeepEqualMemo")(a),f=h(function(){return new(c("BaseTypeaheadBaseStaticDataSource"))(e)},[e]);return h(function(){return{fetchCache:function(a){return d(f.fetchCache(a))}}},[f,d])}g["default"]=a}),98);