;/*FB_PKG_DELIM*/

__d("CometProfileInsightsPostsMainCardQuery$Parameters",["CometProfileInsightsPostsMainCardQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometProfileInsightsPostsMainCardQuery_facebookRelayOperation"),metadata:{},name:"CometProfileInsightsPostsMainCardQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("JSSchedulerLoomProvider",["FBLogger","JSScheduler","gkx","performanceNavigationStart"],(function(a,b,c,d,e,f,g){"use strict";var h=c("gkx")("6196")?0:c("performanceNavigationStart")(),i=1,j=2,k=3,l=4,m=5,n=6,o=7,p=8,q=!0,r=function(){function a(a){a.sequenceNumber===1?this.$1=a:q||(d("JSScheduler").startEventProfiling(),q=!0,this.$1=a)}var b=a.prototype;b.loomTraceWillEnd=function(){var a=this.$1;if(a==null)return;q=!1;var b=d("JSScheduler").stopEventProfiling();if(b==null)return;b=new Int32Array(b);var e=new Map(),f=new Map();for(var g=0;g<=5;g++){var r=0;f.set(g,r);a.buffer.addEvent({type:"JS_SCHEDULER_QUEUE",priority:g,queueSize:r},a.startTime)}r=0;while(r<b.length){g=b[r];var s=h+b[r+1]/1e3;if(g===0)break;else if(g>8){c("FBLogger")("web_loom").warn("Unknown JS Scheduler profiling event: "+g);break}var t=void 0;switch(g){case i:g=b[r+2];var u=b[r+3];e.set(g,u);g=f.get(u);g!=null&&(g+=1,f.set(u,g),t={type:"JS_SCHEDULER_QUEUE",priority:u,queueSize:g});r+=4;break;case j:case k:case l:u=b[r+2];g=e.get(u);if(g!=null){var v=f.get(g);v!=null&&(v-=1,f.set(g,v),t={type:"JS_SCHEDULER_QUEUE",priority:g,queueSize:v});e["delete"](u)}r+=3;break;case o:t={type:"JS_SCHEDULER_QUEUE",priority:0,queueSize:1};r+=3;break;case p:t={type:"JS_SCHEDULER_QUEUE",priority:0,queueSize:0};r+=3;break;case m:case n:r+=4;break}t&&a.buffer.addEvent(t,s)}this.$1=null};return a}();a={loomProviderId:"JSScheduler",isSupported:function(){return!0},getInstance:function(a){return new r(a)}};g["default"]=a}),98);
__d("CometProfileAdCenterRootContentQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5548023231978639"}),null);
__d("LiveProducerLP2ViewerSettingsTabRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4838130586291700"}),null);
__d("PagesCometAdminMessengerToolsHubRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5018271928273655"}),null);
__d("PagesCometEventsAdminRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4942980802487351"}),null);
__d("PagesCometLaunchpointPagesListRedesignedQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5548888428552575"}),null);
__d("PagesCometPagesLikedRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6090142934349663"}),null);
__d("PagesCometPagesYouManageListQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6310877922260514"}),null);
__d("ProfileCometLockedProfileHomeDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4912205825562571"}),null);