;/*FB_PKG_DELIM*/

__d("CometSaveCommunityAttributionSquircle.relayprovider",["gkx"],(function(a,b,c,d,e,f,g){"use strict";a={get:function(){return c("gkx")("7882")}};g["default"]=a}),98);
__d("CometSaveDashboardRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6200891226622342"}),null);
__d("CometSaveDashboardRootQuery$Parameters",["CometSaveCommunityAttributionSquircle.relayprovider","CometSaveDashboardRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometSaveDashboardRootQuery_facebookRelayOperation"),metadata:{},name:"CometSaveDashboardRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__CometSaveCommunityAttributionSquirclerelayprovider:b("CometSaveCommunityAttributionSquircle.relayprovider")}}};e.exports=a}),null);
__d("CometSavePrimaryNavigationQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7964745310264333"}),null);
__d("SaveCollectionsFeatureParityComet.relayprovider",["gkx"],(function(a,b,c,d,e,f,g){"use strict";a={get:function(){return c("gkx")("7185")===!0}};g["default"]=a}),98);
__d("CometSavePrimaryNavigationQuery$Parameters",["CometSavePrimaryNavigationQuery_facebookRelayOperation","SaveCollectionsFeatureParityComet.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometSavePrimaryNavigationQuery_facebookRelayOperation"),metadata:{},name:"CometSavePrimaryNavigationQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__SaveCollectionsFeatureParityCometrelayprovider:b("SaveCollectionsFeatureParityComet.relayprovider")}}};e.exports=a}),null);
__d("buildSaveRoute.entrypoint",["CometSavePrimaryNavigationQuery$Parameters","JSResourceForInteraction","createContentAreaCompoundEntryPointBuilder"],(function(a,b,c,d,e,f,g){"use strict";a=c("createContentAreaCompoundEntryPointBuilder")(c("JSResourceForInteraction")("CometSaveRoot.react").__setRef("buildSaveRoute.entrypoint"),function(a){return{navigationQueryReference:{parameters:b("CometSavePrimaryNavigationQuery$Parameters"),variables:{contributorRoles:["CONTRIBUTOR"]}}}});g["default"]=a}),98);
__d("CometSaveDashboardRoot.entrypoint",["CometSaveDashboardRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildSaveRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildSaveRoute.entrypoint")(c("JSResourceForInteraction")("CometSaveDashboardRoot.react").__setRef("CometSaveDashboardRoot.entrypoint"),function(a){var b=a.routeProps,e=b.content_filter,f=b.referrer;b=b.section;a=a.routeParams;var g=a.hoisted_item_id;a=a.notif_id;return{extraProps:{routeProps:{referrer:f,section:b}},queries:{rootQueryRef:{parameters:c("CometSaveDashboardRootQuery$Parameters"),variables:{content_filter:e!=null?[e]:null,hoisted_item_id:g!=null?String(g):null,notif_id:a!=null?String(a):null,scale:d("WebPixelRatio").get()}}}}});g["default"]=a}),98);
__d("CometSaveLoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({collectionID:null,referrer:null,surface:"dashboard",surfaceGraphQL:"DASHBOARD",surfaceGraphQL_legacy:"dashboard"});g["default"]=b}),98);
__d("useCometSaveLoggingContext",["CometSaveLoggingContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){return h(c("CometSaveLoggingContext"))}g["default"]=a}),98);
__d("XCometSaveDashboardControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/saved/",Object.freeze({unlisted_only:!1}),void 0);b=a;g["default"]=b}),98);
__d("CometSaveCollectionRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5698874250180388"}),null);